# Default values for Calico.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Daemonset Settings
name: calico-node
namespace: kube-system
image:
  node: quay.io/calico/node:v3.3.6
  typha: quay.io/calico/typha:v3.3.6
updateStrategy:
  type: RollingUpdate

failureThreshold: 6

spec:
  hostNetwork: true
  serviceAccountName: calico-node
  terminationGracePeriodSeconds: 0

env:
  # Use Kubernetes API as the backing datastore.
  DATASTORE_TYPE: kubernetes
  FELIX_INTERFACEPREFIX: eni
  # Enable felix info logging.
  FELIX_LOGSEVERITYSCREEN: info
  # Don't enable BGP.
  CALICO_NETWORKING_BACKEND: none
  # Cluster type to identify the deployment type
  CLUSTER_TYPE: k8s,ecs
  # Disable file logging so `kubectl logs` works.
  CALICO_DISABLE_FILE_LOGGING: true
  FELIX_TYPHAK8SSERVICENAME: calico-typha
  # Set Felix endpoint to host default action to ACCEPT.
  FELIX_DEFAULTENDPOINTTOHOSTACTION: ACCEPT
  FELIX_IPTABLESMANGLEALLOWACTION: Return
  # Disable IPV6 on Kubernetes.
  FELIX_IPV6SUPPORT: false
  # Wait for the datastore.
  WAIT_FOR_DATASTORE: true
  FELIX_LOGSEVERITYSYS: none
  FELIX_PROMETHEUSMETRICSENABLED: true
  NO_DEFAULT_POOLS: true
